// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5napFZhA-lsQ0vyBU3s81EoaG6ehyDWg',
    appId: '1:877294522958:android:ed461b54684c72e37a291f',
    messagingSenderId: '877294522958',
    projectId: 'vioraa',
    storageBucket: 'vioraa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBURvKkTfPaPkEpOPqqpooQtPqqp3JO1m0',
    appId: '1:877294522958:ios:808e650ceaba9b32b5dce9',
    messagingSenderId: '877294522958',
    projectId: 'vioraa',
    storageBucket: 'vioraa.firebasestorage.app',
    iosClientId:
        '877294522958-2pjdc36p08ifj5urgbita6h0bo2adlsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetisy',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAonb1TeGeN4zbm3Lige0Dt4KLl2abomU',
    appId: '1:877294522958:web:3eddd3eb09b68e7cb5dce9',
    messagingSenderId: '877294522958',
    projectId: 'vioraa',
    authDomain: 'vioraa.firebaseapp.com',
    storageBucket: 'vioraa.firebasestorage.app',
    measurementId: 'G-766JCSX9CC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBURvKkTfPaPkEpOPqqpooQtPqqp3JO1m0',
    appId: '1:877294522958:ios:808e650ceaba9b32b5dce9',
    messagingSenderId: '877294522958',
    projectId: 'vioraa',
    storageBucket: 'vioraa.firebasestorage.app',
    iosClientId:
        '877294522958-2pjdc36p08ifj5urgbita6h0bo2adlsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetisy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAonb1TeGeN4zbm3Lige0Dt4KLl2abomU',
    appId: '1:877294522958:web:8c1f4993a56f605bb5dce9',
    messagingSenderId: '877294522958',
    projectId: 'vioraa',
    authDomain: 'vioraa.firebaseapp.com',
    storageBucket: 'vioraa.firebasestorage.app',
    measurementId: 'G-MQHG9PMW5L',
  );
}
